### PR TITLE
Grabathon 6.0 Site

### PR DESCRIPTION
**Pull request by yangshun**
Just a copy/paste of 5.0.

### CODE REVIEW

**Comment by paradite** [comment]
who is going to update the 6.0 page?

**Comment by yangshun** [comment]
Good question. Would you like to volunteer? 🌝

**Comment by paradite** [comment]
who is in charge of the Grabathon? I can contact the person. And yes, I can volunteer myself 😆.

**Comment by paradite** [comment]
btw really good design for the page, love it!

**Comment by yangshun** [comment]
You can speak to Tay Yang Heng. He's involved in it again. Anyway... merge it? 😂

**Pull request merged**
